site:
name: Antora Start Page
title: Start Page
version: '1.1'
start_page: page.adoc
content:
  sources:
  - url: https://github.com/Donesrom/techdocs.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true